<a href="https://colab.research.google.com/github/elichen/aoc2022/blob/main/Day_14_Regolith_Reservoir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lines = open("input.txt").readlines()

In [ ]:
# lines = '''498,4 -> 498,6 -> 496,6
# 503,4 -> 502,4 -> 502,9 -> 494,9'''
# lines = lines.split("\n")

In [ ]:
lines = [x.strip() for x in lines]

In [ ]:
x_low, x_high = 2**10, -1
y_low, y_high = 0, -1
for line in lines:
  pairs = line.split(" -> ")
  for pair in pairs:
    x,y = map(int,pair.split(","))
    x_low, x_high = min(x,x_low), max(x,x_high)
    y_high = max(y,y_high)
x_low, x_high, y_low, y_high

(490, 573, 0, 182)

In [ ]:
import numpy as np
m = np.zeros([ y_high+1, x_high-x_low+1])

for line in lines:
  pairs = line.split(" -> ")
  prev_pair = None
  for pair in pairs:
    x,y = map(int,pair.split(","))
    if prev_pair:
      x_range = min(prev_pair[0],x) - x_low, max(prev_pair[0],x)+1 - x_low
      y_range = min(prev_pair[1],y), max(prev_pair[1],y)+1
      for i in range(*x_range):
        for j in range(*y_range):
          m[j,i] = 1
    prev_pair = (x,y)
m

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
m.shape

(183, 84)

In [ ]:
def simulate():
  total = 0
  while True:
    sand = (500-x_low,0)
    while True:
      # print(sand)
      if sand[1]+1 < m.shape[0]:
        if m[sand[1]+1,sand[0]] == 0:
          sand = sand[0],sand[1]+1
          continue
        if sand[0]-1 < 0:
          # print("fell off left")
          return total
        if m[sand[1]+1,sand[0]-1] == 0:
          sand = sand[0]-1,sand[1]+1
          continue
        if sand[0]+1 > m.shape[1]:
          # print("fell off right")
          return total
        if m[sand[1]+1,sand[0]+1] == 0:
          sand = sand[0]+1,sand[1]+1
          continue
        # print("splat!")
        total += 1
        m[sand[1],sand[0]] = 2
        break
      else:
        # print("fell off bottom")
        return total
simulate()

964

In [ ]:
lines += [f"{x_low-y_high},{y_high+2} -> {x_high+y_high},{y_high+2}"]

In [ ]:
x_low, x_high = 2**10, -1
y_low, y_high = 0, -1
for line in lines:
  pairs = line.split(" -> ")
  for pair in pairs:
    x,y = map(int,pair.split(","))
    x_low, x_high = min(x,x_low), max(x,x_high)
    y_high = max(y,y_high)
x_low, x_high, y_low, y_high

(308, 755, 0, 184)

In [ ]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))
m = np.zeros([ y_high+1, x_high-x_low+1])
print(m.shape)

for line in lines:
  pairs = line.split(" -> ")
  prev_pair = None
  for pair in pairs:
    x,y = map(int,pair.split(","))
    if prev_pair:
      x_range = min(prev_pair[0],x) - x_low, max(prev_pair[0],x)+1 - x_low
      y_range = min(prev_pair[1],y), max(prev_pair[1],y)+1
      for i in range(*x_range):
        for j in range(*y_range):
          m[j,i] = 1
    prev_pair = (x,y)
m

(185, 448)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [ ]:
def simulate():
  total = 0
  while True:
    sand = (500-x_low,0)
    if not m[sand[1],sand[0]] == 0:
      print("full!")
      return total
    while True:
      # print(sand)
      if sand[1]+1 < m.shape[0]:
        if m[sand[1]+1,sand[0]] == 0:
          sand = sand[0],sand[1]+1
          continue
        if sand[0]-1 < 0:
          print("fell off left")
          return total
        if m[sand[1]+1,sand[0]-1] == 0:
          sand = sand[0]-1,sand[1]+1
          continue
        if sand[0]+1 >= m.shape[1]:
          print("fell off right")
          return total
        if m[sand[1]+1,sand[0]+1] == 0:
          sand = sand[0]+1,sand[1]+1
          continue
        # print("splat!")
        total += 1
        m[sand[1],sand[0]] = 2
        break
      else:
        print("fell off bottom")
        return total
simulate()

full!


32041

In [ ]:
m

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0